name: webcontent_converter_platform_interface
description: A common platform interface for the webcontent_converter plugin.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.4.1
